export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const USER_LOGGED = "USER_LOGGED";
export const USER_NOT_LOGGED = "USER_NOT_LOGGED";
export const LOGOUT_USER = "LOGOUT_USER";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_SELLER_PRODUCTS = "GET_SELLER_PRODUCTS"

